# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mkdir publish
      cp -r static/* publish
      cd publish
      az artifacts universal publish --organization https://dev.azure.com/DevOps-Batches/ --project="DevOps51"  --scope project --feed devopsb51 --name frontend --version 0.0.1 --description "Roboshop Frontend" --path .
      