apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-BUILDNO
  labels:
    app: roboshop
    tier: frontend
    build: "BUILDNO"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
      build: "BUILDNO"
  template:
    metadata:
      labels:
        tier: frontend
        build: "BUILDNO"
    spec:
      containers:
        - name: frontend
          image: rkalluru/b48-frontend:BUILDNO
          ports:
            - containerPort: 80
