apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    tier: frontend
    build: "BUILDNO"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
